package com.myjavagame.model;

import lombok.Data;

@Data
public class Player {
    private String login;

    // Constructors

    public Player() {
        // Default constructor
    }

    public Player(String login) {
        this.login = login;
    }

    // Getters and setters (generated by Lombok)

    // Other methods (if needed)

    @Override
    public String toString() {
        return "Player{" +
                "login='" + login + '\'' +
                '}';
    }
}

